//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptekaEntities : DbContext
    {
        public AptekaEntities()
            : base("name=AptekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<Faktury_Dostawców> Faktury_Dostawców { get; set; }
        public virtual DbSet<Farmaceuci> Farmaceuci { get; set; }
        public virtual DbSet<Grafiki_Pracowników> Grafiki_Pracowników { get; set; }
        public virtual DbSet<Kategorie_Leków> Kategorie_Leków { get; set; }
        public virtual DbSet<Leki> Leki { get; set; }
        public virtual DbSet<Magazyn> Magazyn { get; set; }
        public virtual DbSet<Pacjenci> Pacjenci { get; set; }
        public virtual DbSet<Paragony> Paragony { get; set; }
        public virtual DbSet<Producent_Leków> Producent_Leków { get; set; }
        public virtual DbSet<Produkty_Zamówienia> Produkty_Zamówienia { get; set; }
        public virtual DbSet<Raporty_Sprzedaży> Raporty_Sprzedaży { get; set; }
        public virtual DbSet<Recepty> Recepty { get; set; }
        public virtual DbSet<Sprzedaż> Sprzedaż { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zamówienia> Zamówienia { get; set; }
    }
}
