//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grafiki_Pracowników
    {
        public int ID_Grafiku { get; set; }
        public int ID_Farmaceuty { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Godzina_Rozpoczęcia { get; set; }
        public System.TimeSpan Godzina_Zakończenia { get; set; }
    
        public virtual Farmaceuci Farmaceuci { get; set; }
    }
}
