//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leki()
        {
            this.Magazyn = new HashSet<Magazyn>();
            this.Produkty_Zamówienia = new HashSet<Produkty_Zamówienia>();
            this.Sprzedaż = new HashSet<Sprzedaż>();
        }
    
        public int ID_Leku { get; set; }
        public string Nazwa_Leku { get; set; }
        public int ID_Kategorii { get; set; }
        public decimal Cena_Zakupu { get; set; }
        public decimal Cena_Sprzedaży { get; set; }
        public System.DateTime Data_Waznosci { get; set; }
        public int ID_Producenta { get; set; }
        public bool Na_Recepte { get; set; }
        public bool Refundacja { get; set; }
        public string Opis { get; set; }
    
        public virtual Kategorie_Leków Kategorie_Leków { get; set; }
        public virtual Producent_Leków Producent_Leków { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazyn> Magazyn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkty_Zamówienia> Produkty_Zamówienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaż> Sprzedaż { get; set; }
    }
}
