//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paragony
    {
        public int ID_Paragonu { get; set; }
        public string Numer_Paragonu { get; set; }
        public int ID_Sprzedaży { get; set; }
        public System.DateTime Data_Wystawienia { get; set; }
        public decimal Kwota { get; set; }
    
        public virtual Sprzedaż Sprzedaż { get; set; }
    }
}
