//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producent_Leków
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producent_Leków()
        {
            this.Leki = new HashSet<Leki>();
        }
    
        public int ID_Producenta { get; set; }
        public string Nazwa_Producenta { get; set; }
        public string Telefon { get; set; }
        public string Ulica { get; set; }
        public string Miasto { get; set; }
        public string Kod_Pocztowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leki> Leki { get; set; }
    }
}
