//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty_Zamówienia
    {
        public int ID_Produktu_Zamówienia { get; set; }
        public int ID_Zamówienia { get; set; }
        public int ID_Leku { get; set; }
        public int Ilość { get; set; }
    
        public virtual Leki Leki { get; set; }
        public virtual Zamówienia Zamówienia { get; set; }
    }
}
