//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaż
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprzedaż()
        {
            this.Paragony = new HashSet<Paragony>();
        }
    
        public int ID_Sprzedaży { get; set; }
        public int ID_Leku { get; set; }
        public Nullable<int> ID_Pacjenta { get; set; }
        public System.DateTime Data_Sprzedaży { get; set; }
        public decimal Kwota { get; set; }
        public string Forma_Płatności { get; set; }
    
        public virtual Leki Leki { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paragony> Paragony { get; set; }
    }
}
