//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienia()
        {
            this.Faktury_Dostawców = new HashSet<Faktury_Dostawców>();
            this.Produkty_Zamówienia = new HashSet<Produkty_Zamówienia>();
        }
    
        public int ID_Zamówienia { get; set; }
        public int ID_Dostawcy { get; set; }
        public System.DateTime Data_Zamówienia { get; set; }
        public System.DateTime Data_Dostawy { get; set; }
        public string Status { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury_Dostawców> Faktury_Dostawców { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produkty_Zamówienia> Produkty_Zamówienia { get; set; }
    }
}
